rootProject.name = "ESU"
include("core")
include("bukkit")
include("velocity")
include("bungeecord")

include("bukkit:version")
include("bukkit:version:v1_17_1")
include("bukkit:version:v1_18")
include("bukkit:version:v1_20")
include("bukkit:version:v1_20_2")
include("bukkit:version:v1_21")
include("bukkit:version:v1_21_3")
include("bukkit:version:v1_21_6")
include("bukkit:version:base")