rootProject.name = "ESU"
include("core")
include("core:dep-core")
include("core:dep-impl-core")

include("bukkit")
include("bukkit:dep-bukkit")
include("bukkit:version")
include("bukkit:version:base")
include("bukkit:version:v1_17_1")
include("bukkit:version:v1_18")
include("bukkit:version:v1_20")
include("bukkit:version:v1_20_2")
include("bukkit:version:v1_20_4")
include("bukkit:version:v1_21")
include("bukkit:version:v1_21_1")
include("bukkit:version:v1_21_3")
include("bukkit:version:v1_21_6")

include("velocity")