name: ESU
main: io.github.rothes.esu.bukkit.EsuPluginBukkit
version: @versionName@
api-version: 1.19
author: Rothes
folia-supported: true
softdepend:
  - PlugMan
permissions:
  'esu.chatantispam.bypass':
    default: op
  'esu.chatantispam.notify':
    default: op
  'esu.anticommandspam.exempt':
    default: op