name: ESU
main: io.github.rothes.esu.bukkit.EsuPluginBukkit
version: @versionName@
api-version: 1.13
author: Rothes
folia-supported: true
softdepend:
  - Authme
  - CraftEngine
  - PlugMan
  - packetevents

permissions:
  'esu.chatAntiSpam.bypass':
    default: op
  'esu.chatAntiSpam.notify':
    default: op
  'esu.antiCommandSpam.exempt':
    default: op
  'esu.esuChat.spy':
    default: op
  'esu.esuChat.spy.other':
    default: op
  'esu.esuChat.spy.enableOnJoin':
    default: op