name: ESU
main: io.github.rothes.esu.bukkit.EsuPluginBukkit
version: @versionName@
api-version: 1.13
author: Rothes
folia-supported: true
softdepend:
  - Authme
  - CraftEngine
  - PlugMan
  - packetevents

permissions:
  'esu.antiCommandSpam.admin':
    default: op
    children:
      'esu.antiCommandSpam.exempt': true

  'esu.chatAntiSpam.admin':
    default: op
    children:
      'esu.chatAntiSpam.bypass': true
      'esu.chatAntiSpam.notify': true

  'esu.esuChat.chat.shout':
    default: true
  'esu.esuChat.admin':
    default: op
    children:
      'esu.esuChat.spy': true
      'esu.esuChat.spy.other': true
      'esu.esuChat.spy.enableOnJoin': true

  'esu.networkThrottle.admin':
    default: op
    children:
      'esu.networkThrottle.command.analyser': true
      'esu.networkThrottle.command.chunkDataThrottle': true

  'esu.news.admin':
    default: op
    children:
      'esu.news.command.editor': true

  'esu.utilCommands.admin':
    default: op
    children:
      'esu.utilCommands.command.ping': true
      'esu.utilCommands.command.clientLocale': true
      'esu.utilCommands.command.ip': true
      'esu.utilCommands.command.ipGroup': true
      'esu.utilCommands.command.tpChunk': true
      'esu.utilCommands.command.genRateTop': true
      'esu.utilCommands.command.loadRateTop': true